# Generated by Django 4.2.5 on 2023-09-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugitem',
            name='inStock',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='drugitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
